-- Кодекс Майстра: фінальні demo seed дані для MVP.
-- Запускати після supabase/schema.sql. Тексти короткі, оригінальні й призначені тільки для перевірки UI.

insert into public.sections (title, slug, description, image_url, sort_order, is_published)
values
  ('Раси', 'races', 'Тип істоти, розмір, швидкість, мови та расові риси.', null, 10, true),
  ('Класи', 'classes', 'Кістка хітів, ряткидки, володіння та класові особливості.', null, 20, true),
  ('Предмети', 'items', 'Зброя, броня, спорядження, властивості та ціна.', null, 30, true)
on conflict (slug) do update
set title = excluded.title,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published,
    updated_at = now();

insert into public.sources (title, source_type, url, comment)
values
  ('SRD 5.2 Reference', 'official', null, 'На основі відкритих правил SRD. Текст адаптовано українською для довідника.'),
  ('Авторський матеріал', 'homebrew', null, 'Джерело для матеріалів кампанії або homebrew.')
on conflict (title, source_type) do update
set comment = excluded.comment,
    updated_at = now();

insert into public.races (
  title_ua,
  title_original,
  slug,
  short_description,
  full_description_markdown,
  image_url,
  source_id,
  tags,
  publication_status,
  rules_version,
  content_type,
  creature_type,
  size,
  speed,
  languages,
  lifespan,
  alignment_or_behavior,
  race_traits,
  ability_bonuses,
  proficiencies,
  additional_skills,
  subraces
)
values
  (
    'Людина',
    'Human',
    'human',
    'Раса гуманоїдів. Розмір: Середній. Швидкість: 30 фт.',
    E'## Людина\nБазові правила: тип істоти гуманоїд, розмір Середній, швидкість 30 фт.\n\nМови: Спільна та одна додаткова мова.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['раса', 'гуманоїд', 'середній'],
    'published',
    '2024',
    'official',
    'гуманоїд',
    'Середній',
    '30 фт',
    array['Спільна', 'одна додаткова мова'],
    'до 100 років',
    'не визначено правилами',
    '[{"name":"Додаткова мова","mechanical_effect":"Володіння однією додатковою мовою.","usage":"Постійно"}]'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '["одне вміння на вибір"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'Ельф',
    'Elf',
    'elf',
    'Раса гуманоїдів. Розмір: Середній. Швидкість: 30 фт.',
    E'## Ельф\nБазові правила: тип істоти гуманоїд, розмір Середній, швидкість 30 фт.\n\nМови: Спільна та Ельфійська.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['раса', 'гуманоїд', 'ельф'],
    'published',
    '2024',
    'official',
    'гуманоїд',
    'Середній',
    '30 фт',
    array['Спільна', 'Ельфійська'],
    'до 750 років',
    'не визначено правилами',
    '[{"name":"Темний зір","mechanical_effect":"Темний зір: 60 футів.","usage":"Постійно"},{"name":"Спадок фей","mechanical_effect":"Перевага на ряткидки проти стану зачарований.","usage":"Постійно","saving_throw_advantages":"проти стану зачарований"}]'::jsonb,
    '{}'::jsonb,
    '{"skills":["Уважність"]}'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb
  ),
  (
    'Дворф',
    'Dwarf',
    'dwarf',
    'Раса гуманоїдів. Розмір: Середній. Швидкість: 25 фт.',
    E'## Дворф\nБазові правила: тип істоти гуманоїд, розмір Середній, швидкість 25 фт.\n\nМови: Спільна та Дворфійська.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['раса', 'гуманоїд', 'дворф'],
    'published',
    '2024',
    'official',
    'гуманоїд',
    'Середній',
    '25 фт',
    array['Спільна', 'Дворфійська'],
    'до 350 років',
    'не визначено правилами',
    '[{"name":"Темний зір","mechanical_effect":"Темний зір: 60 футів.","usage":"Постійно"},{"name":"Стійкість до отрути","mechanical_effect":"Перевага на ряткидки проти отрути та стійкість до отруйної шкоди.","usage":"Постійно","saving_throw":"Статура","resistance":"отруйна шкода"}]'::jsonb,
    '{}'::jsonb,
    '{"tools":["ремісничий інструмент на вибір"]}'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb
  )
on conflict (slug) do update
set title_ua = excluded.title_ua,
    title_original = excluded.title_original,
    short_description = excluded.short_description,
    full_description_markdown = excluded.full_description_markdown,
    source_id = excluded.source_id,
    tags = excluded.tags,
    publication_status = excluded.publication_status,
    rules_version = excluded.rules_version,
    content_type = excluded.content_type,
    creature_type = excluded.creature_type,
    size = excluded.size,
    speed = excluded.speed,
    languages = excluded.languages,
    lifespan = excluded.lifespan,
    alignment_or_behavior = excluded.alignment_or_behavior,
    race_traits = excluded.race_traits,
    ability_bonuses = excluded.ability_bonuses,
    proficiencies = excluded.proficiencies,
    additional_skills = excluded.additional_skills,
    subraces = excluded.subraces,
    updated_at = now();

insert into public.classes (
  title_ua,
  title_original,
  slug,
  short_description,
  full_description_markdown,
  image_url,
  source_id,
  tags,
  publication_status,
  rules_version,
  content_type,
  hit_die,
  primary_ability,
  saving_throws,
  armor_proficiencies,
  weapon_proficiencies,
  tool_proficiencies,
  skill_choices,
  starting_equipment,
  class_features,
  class_progression,
  subclasses,
  spellcasting,
  has_spellcasting
)
values
  (
    'Плут',
    'Rogue',
    'rogue',
    'Клас. Кістка хітів: d8. Основна характеристика: Спритність.',
    E'## Плут\nКістка хітів: d8. Основна характеристика: Спритність.\n\nРяткидки: Спритність, Інтелект.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['клас', 'спритність', 'скритність'],
    'published',
    '2024',
    'official',
    'd8',
    'Спритність',
    array['Спритність', 'Інтелект'],
    array['легка броня'],
    array['проста зброя', 'точна зброя'],
    array['інструменти злодія'],
    '{"choose":2,"from":["скритність","спритність рук","переконання","обман"]}'::jsonb,
    '[{"name":"легка броня"},{"name":"інструменти злодія"}]'::jsonb,
    '[{"level":1,"name":"Прихована атака","mechanical_effect":"Раз на хід додає додаткову шкоду, якщо атака має перевагу або союзник цілі перебуває поруч із нею.","usage":"Раз на хід","scaling":"Шкода зростає з рівнем"}]'::jsonb,
    '[{"level":1,"bonus":"+2"},{"level":2,"bonus":"+2"}]'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    false
  ),
  (
    'Варвар',
    'Barbarian',
    'barbarian',
    'Клас. Кістка хітів: d12. Основна характеристика: Сила.',
    E'## Варвар\nКістка хітів: d12. Основна характеристика: Сила.\n\nРяткидки: Сила, Статура.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['клас', 'сила', 'витривалість'],
    'published',
    '2024',
    'official',
    'd12',
    'Сила',
    array['Сила', 'Статура'],
    array['легка броня', 'середня броня', 'щити'],
    array['проста зброя', 'військова зброя'],
    array[]::text[],
    '{"choose":2,"from":["атлетика","виживання","залякування"]}'::jsonb,
    '[{"name":"бойова зброя"},{"name":"дорожній набір"}]'::jsonb,
    '[{"level":1,"name":"Лють","mechanical_effect":"Перевага на перевірки й ряткидки Сили; бонус до шкоди атакою Силою; стійкість до дробильної, колотої та рубаної шкоди.","usage":"Бонусна дія"}]'::jsonb,
    '[{"level":1,"bonus":"+2"},{"level":2,"bonus":"+2"}]'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    false
  ),
  (
    'Чарівник',
    'Wizard',
    'wizard',
    'Клас. Кістка хітів: d6. Заклинальна характеристика: Інтелект.',
    E'## Чарівник\nКістка хітів: d6. Заклинальна характеристика: Інтелект.\n\nРяткидки: Інтелект, Мудрість.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['клас', 'інтелект', 'магія'],
    'published',
    '2024',
    'official',
    'd6',
    'Інтелект',
    array['Інтелект', 'Мудрість'],
    array[]::text[],
    array['посох', 'кинджал'],
    array['набір письма'],
    '{"choose":2,"from":["арканознавство","історія","аналіз"]}'::jsonb,
    '[{"name":"книга нотаток"},{"name":"фокус для заклять"}]'::jsonb,
    '[{"level":1,"name":"Заклинання","mechanical_effect":"Використовує Інтелект як заклинальну характеристику.","usage":"За правилами заклинань"}]'::jsonb,
    '[{"level":1,"slots":2},{"level":2,"slots":3}]'::jsonb,
    '[]'::jsonb,
    '{"ability":"Інтелект","focus":"книга або фокус"}'::jsonb,
    true
  )
on conflict (slug) do update
set title_ua = excluded.title_ua,
    title_original = excluded.title_original,
    short_description = excluded.short_description,
    full_description_markdown = excluded.full_description_markdown,
    source_id = excluded.source_id,
    tags = excluded.tags,
    publication_status = excluded.publication_status,
    rules_version = excluded.rules_version,
    content_type = excluded.content_type,
    hit_die = excluded.hit_die,
    primary_ability = excluded.primary_ability,
    saving_throws = excluded.saving_throws,
    armor_proficiencies = excluded.armor_proficiencies,
    weapon_proficiencies = excluded.weapon_proficiencies,
    tool_proficiencies = excluded.tool_proficiencies,
    skill_choices = excluded.skill_choices,
    starting_equipment = excluded.starting_equipment,
    class_features = excluded.class_features,
    class_progression = excluded.class_progression,
    subclasses = excluded.subclasses,
    spellcasting = excluded.spellcasting,
    has_spellcasting = excluded.has_spellcasting,
    updated_at = now();

insert into public.items (
  title_ua,
  title_original,
  slug,
  short_description,
  full_description_markdown,
  image_url,
  source_id,
  tags,
  publication_status,
  rules_version,
  content_type,
  item_type,
  category,
  rarity,
  price,
  weight,
  requires_attunement,
  is_magical,
  properties,
  damage,
  damage_type,
  range,
  armor_class,
  required_strength,
  stealth_disadvantage,
  quantity
)
values
  (
    'Довгий меч',
    'Longsword',
    'longsword',
    'Бойова зброя ближнього бою. Шкода: 1d8 рубана.',
    E'## Довгий меч\nБойова зброя ближнього бою.\n\nШкода: 1d8 рубана. Властивість: універсальна 1d10.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['предмет', 'зброя', 'меч'],
    'published',
    '2024',
    'official',
    'зброя',
    'військова',
    'звичайний',
    '15 зм',
    '3 фунти',
    false,
    false,
    '{"versatile":true}'::jsonb,
    '1d8',
    'рубана',
    'ближній бій',
    null,
    null,
    false,
    '1'
  ),
  (
    'Шкіряна броня',
    'Leather Armor',
    'leather-armor',
    'Легка броня. Клас захисту: 11 + модифікатор Спритності.',
    E'## Шкіряна броня\nЛегка броня.\n\nКлас захисту: 11 + модифікатор Спритності. Перешкода: Скритність — ні.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['предмет', 'броня', 'легка'],
    'published',
    '2024',
    'official',
    'броня',
    'легка',
    'звичайний',
    '10 зм',
    '10 фунтів',
    false,
    false,
    '{}'::jsonb,
    null,
    null,
    null,
    '11 + модифікатор Спритності',
    null,
    false,
    '1'
  ),
  (
    'Набір мандрівника',
    'Adventurer’s Pack',
    'adventurers-pack',
    'Спорядження мандрівника. Кількість: 1 набір.',
    E'## Набір мандрівника\nСпорядження мандрівника.\n\nВміст вказано у властивостях предмета.',
    null,
    (select id from public.sources where title = 'SRD 5.2 Reference' and source_type = 'official' limit 1),
    array['предмет', 'спорядження', 'подорож'],
    'published',
    '2024',
    'homebrew',
    'спорядження',
    'пригодницьке',
    'звичайний',
    '12 зм',
    '8 фунтів',
    false,
    false,
    '{"contains":["мотузка","кресало","сухий пайок"]}'::jsonb,
    null,
    null,
    null,
    null,
    null,
    false,
    '1 набір'
  )
on conflict (slug) do update
set title_ua = excluded.title_ua,
    title_original = excluded.title_original,
    short_description = excluded.short_description,
    full_description_markdown = excluded.full_description_markdown,
    source_id = excluded.source_id,
    tags = excluded.tags,
    publication_status = excluded.publication_status,
    rules_version = excluded.rules_version,
    content_type = excluded.content_type,
    item_type = excluded.item_type,
    category = excluded.category,
    rarity = excluded.rarity,
    price = excluded.price,
    weight = excluded.weight,
    requires_attunement = excluded.requires_attunement,
    is_magical = excluded.is_magical,
    properties = excluded.properties,
    damage = excluded.damage,
    damage_type = excluded.damage_type,
    range = excluded.range,
    armor_class = excluded.armor_class,
    required_strength = excluded.required_strength,
    stealth_disadvantage = excluded.stealth_disadvantage,
    quantity = excluded.quantity,
    updated_at = now();
