-- Кодекс Майстра: фінальні demo seed дані для MVP.
-- Запускати після supabase/schema.sql. Тексти короткі, оригінальні й призначені тільки для перевірки UI.

insert into public.sections (title, slug, description, image_url, sort_order, is_published)
values
  ('Раси', 'races', 'Походження, риси та культурні акценти персонажів.', null, 10, true),
  ('Класи', 'classes', 'Архетипи героїв, бойові ролі та ключові здібності.', null, 20, true),
  ('Предмети', 'items', 'Спорядження, зброя, броня та корисні речі для пригод.', null, 30, true)
on conflict (slug) do update
set title = excluded.title,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published,
    updated_at = now();

insert into public.sources (title, source_type, url, comment)
values
  ('Demo 2024', 'official', null, 'Демонстраційне джерело для матеріалів версії правил 2024. Не містить скопійованого тексту.'),
  ('Homebrew Demo', 'homebrew', null, 'Демонстраційне джерело для авторських матеріалів.')
on conflict (title, source_type) do update
set comment = excluded.comment,
    updated_at = now();

insert into public.races (
  title_ua,
  title_original,
  slug,
  short_description,
  full_description_markdown,
  image_url,
  source_id,
  tags,
  publication_status,
  rules_version,
  content_type,
  creature_type,
  size,
  speed,
  languages,
  lifespan,
  alignment_or_behavior,
  race_traits,
  ability_bonuses,
  proficiencies,
  additional_skills,
  subraces
)
values
  (
    'Людина',
    'Human',
    'human',
    'Гнучкі й винахідливі мандрівники, які швидко пристосовуються до нових земель.',
    E'## Людина\nЛюди легко знаходять місце у різних громадах і часто стають рушієм змін у пригодах.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['раса', 'універсальність', 'соціальність'],
    'published',
    '2024',
    'official',
    'гуманоїд',
    'Середній',
    '30 фт',
    array['Спільна', 'одна додаткова'],
    'близько століття',
    'часто діють через допитливість і прагнення впливати на світ',
    '[{"name":"Швидке навчання","description":"Може швидко опанувати новий підхід або ремесло."}]'::jsonb,
    '{"flexible":true}'::jsonb,
    '{"tools":["один інструмент на вибір"]}'::jsonb,
    '["одне вміння на вибір"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'Ельф',
    'Elf',
    'elf',
    'Зосереджені довгожителі з тонким чуттям до краси, пам’яті й магічних слідів.',
    E'## Ельф\nЕльфи уважно читають світ навколо себе й часто помічають деталі, які інші пропускають.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['раса', 'сприйняття', 'магія'],
    'published',
    '2024',
    'official',
    'гуманоїд',
    'Середній',
    '30 фт',
    array['Спільна', 'Ельфійська'],
    'кілька століть',
    'часто цінують витримку, традицію та особисту майстерність',
    '[{"name":"Тонке чуття","description":"Помічає слабкі ознаки небезпеки або магічного впливу."}]'::jsonb,
    '{"graceful":true}'::jsonb,
    '{"skills":["уважність"]}'::jsonb,
    '[]'::jsonb,
    '[{"name":"Лісовий варіант","note":"Підходить для кампаній із дикими землями."}]'::jsonb
  ),
  (
    'Дворф',
    'Dwarf',
    'dwarf',
    'Стійкі майстри каменю й металу, які цінують пам’ять роду та чесну працю.',
    E'## Дворф\nДворфи впевнено тримають позицію й добре розуміють ціну надійного спорядження.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['раса', 'витривалість', 'ремесло'],
    'published',
    '2024',
    'official',
    'гуманоїд',
    'Середній',
    '25 фт',
    array['Спільна', 'Дворфійська'],
    'понад два століття',
    'часто поважають обіцянки, майстерність і стійкість',
    '[{"name":"Кам’яна пам’ять","description":"Має добру інтуїцію щодо підземель, каменю та старої кладки."}]'::jsonb,
    '{"sturdy":true}'::jsonb,
    '{"tools":["ремісничий інструмент"]}'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb
  )
on conflict (slug) do update
set title_ua = excluded.title_ua,
    title_original = excluded.title_original,
    short_description = excluded.short_description,
    full_description_markdown = excluded.full_description_markdown,
    source_id = excluded.source_id,
    tags = excluded.tags,
    publication_status = excluded.publication_status,
    rules_version = excluded.rules_version,
    content_type = excluded.content_type,
    creature_type = excluded.creature_type,
    size = excluded.size,
    speed = excluded.speed,
    languages = excluded.languages,
    lifespan = excluded.lifespan,
    alignment_or_behavior = excluded.alignment_or_behavior,
    race_traits = excluded.race_traits,
    ability_bonuses = excluded.ability_bonuses,
    proficiencies = excluded.proficiencies,
    additional_skills = excluded.additional_skills,
    subraces = excluded.subraces,
    updated_at = now();

insert into public.classes (
  title_ua,
  title_original,
  slug,
  short_description,
  full_description_markdown,
  image_url,
  source_id,
  tags,
  publication_status,
  rules_version,
  content_type,
  hit_die,
  primary_ability,
  saving_throws,
  armor_proficiencies,
  weapon_proficiencies,
  tool_proficiencies,
  skill_choices,
  starting_equipment,
  class_features,
  class_progression,
  subclasses,
  spellcasting,
  has_spellcasting
)
values
  (
    'Плут',
    'Rogue',
    'rogue',
    'Спритний фахівець, який покладається на точність, тишу й швидке рішення.',
    E'## Плут\nПлут добре почувається там, де потрібні обережність, хитрість і влучний момент.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['клас', 'спритність', 'скритність'],
    'published',
    '2024',
    'official',
    'd8',
    'Спритність',
    array['Спритність', 'Інтелект'],
    array['легка броня'],
    array['проста зброя', 'точна зброя'],
    array['інструменти злодія'],
    '{"choose":2,"from":["скритність","спритність рук","переконання","обман"]}'::jsonb,
    '[{"name":"легка броня"},{"name":"інструменти злодія"}]'::jsonb,
    '[{"level":1,"name":"Точний удар","description":"Краще використовує перевагу позиції."}]'::jsonb,
    '[{"level":1,"bonus":"+2"},{"level":2,"bonus":"+2"}]'::jsonb,
    '[{"name":"Тіньовий шлях","note":"Демо-підклас для перевірки UI."}]'::jsonb,
    '{}'::jsonb,
    false
  ),
  (
    'Варвар',
    'Barbarian',
    'barbarian',
    'Невтомний воїн, який перетворює лють і витривалість на захист союзників.',
    E'## Варвар\nВарвар стоїть на передній лінії та приймає удар, коли інші шукають кращу позицію.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['клас', 'сила', 'витривалість'],
    'published',
    '2024',
    'official',
    'd12',
    'Сила',
    array['Сила', 'Статура'],
    array['легка броня', 'середня броня', 'щити'],
    array['проста зброя', 'військова зброя'],
    array[]::text[],
    '{"choose":2,"from":["атлетика","виживання","залякування"]}'::jsonb,
    '[{"name":"бойова зброя"},{"name":"дорожній набір"}]'::jsonb,
    '[{"level":1,"name":"Бойовий запал","description":"Короткий спалах сили у небезпечний момент."}]'::jsonb,
    '[{"level":1,"bonus":"+2"},{"level":2,"bonus":"+2"}]'::jsonb,
    '[{"name":"Шлях грому","note":"Демо-варіант для кампаній."}]'::jsonb,
    '{}'::jsonb,
    false
  ),
  (
    'Чарівник',
    'Wizard',
    'wizard',
    'Учений маг, який збирає знання й обережно перетворює їх на силу.',
    E'## Чарівник\nЧарівник розв’язує проблеми підготовкою, нотатками та точним використанням магії.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['клас', 'інтелект', 'магія'],
    'published',
    '2024',
    'official',
    'd6',
    'Інтелект',
    array['Інтелект', 'Мудрість'],
    array[]::text[],
    array['посох', 'кинджал'],
    array['набір письма'],
    '{"choose":2,"from":["арканознавство","історія","аналіз"]}'::jsonb,
    '[{"name":"книга нотаток"},{"name":"фокус для заклять"}]'::jsonb,
    '[{"level":1,"name":"Підготовлена формула","description":"Може тримати кілька магічних рішень напоготові."}]'::jsonb,
    '[{"level":1,"slots":2},{"level":2,"slots":3}]'::jsonb,
    '[{"name":"Школа знаків","note":"Демо-напрям для перевірки JSONB."}]'::jsonb,
    '{"ability":"Інтелект","focus":"книга або фокус"}'::jsonb,
    true
  )
on conflict (slug) do update
set title_ua = excluded.title_ua,
    title_original = excluded.title_original,
    short_description = excluded.short_description,
    full_description_markdown = excluded.full_description_markdown,
    source_id = excluded.source_id,
    tags = excluded.tags,
    publication_status = excluded.publication_status,
    rules_version = excluded.rules_version,
    content_type = excluded.content_type,
    hit_die = excluded.hit_die,
    primary_ability = excluded.primary_ability,
    saving_throws = excluded.saving_throws,
    armor_proficiencies = excluded.armor_proficiencies,
    weapon_proficiencies = excluded.weapon_proficiencies,
    tool_proficiencies = excluded.tool_proficiencies,
    skill_choices = excluded.skill_choices,
    starting_equipment = excluded.starting_equipment,
    class_features = excluded.class_features,
    class_progression = excluded.class_progression,
    subclasses = excluded.subclasses,
    spellcasting = excluded.spellcasting,
    has_spellcasting = excluded.has_spellcasting,
    updated_at = now();

insert into public.items (
  title_ua,
  title_original,
  slug,
  short_description,
  full_description_markdown,
  image_url,
  source_id,
  tags,
  publication_status,
  rules_version,
  content_type,
  item_type,
  category,
  rarity,
  price,
  weight,
  requires_attunement,
  is_magical,
  properties,
  damage,
  damage_type,
  range,
  armor_class,
  required_strength,
  stealth_disadvantage,
  quantity
)
values
  (
    'Довгий меч',
    'Longsword',
    'longsword',
    'Надійна зброя для воїна, який цінує баланс між контролем і силою.',
    E'## Довгий меч\nКласична клинкова зброя для перевірки карток, фільтрів і detail page.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['предмет', 'зброя', 'меч'],
    'published',
    '2024',
    'official',
    'зброя',
    'військова',
    'звичайний',
    '15 зм',
    '3 фунти',
    false,
    false,
    '{"versatile":true}'::jsonb,
    '1d8',
    'рубаний',
    'ближній бій',
    null,
    null,
    false,
    '1'
  ),
  (
    'Шкіряна броня',
    'Leather Armor',
    'leather-armor',
    'Легка броня для тих, кому важливі рухливість і базовий захист.',
    E'## Шкіряна броня\nПроста броня для мандрівника, який не хоче втрачати швидкість.',
    null,
    (select id from public.sources where title = 'Demo 2024' and source_type = 'official' limit 1),
    array['предмет', 'броня', 'легка'],
    'published',
    '2024',
    'official',
    'броня',
    'легка',
    'звичайний',
    '10 зм',
    '10 фунтів',
    false,
    false,
    '{"flexible":true}'::jsonb,
    null,
    null,
    null,
    '11 + модифікатор спритності',
    null,
    false,
    '1'
  ),
  (
    'Набір мандрівника',
    'Traveler Kit',
    'traveler-kit',
    'Компактний набір дрібниць для короткої дороги й першої ночівлі.',
    E'## Набір мандрівника\nКорисний пакунок для старту пригоди: мотузка, кресало, сухий пайок і кілька дрібних речей.',
    null,
    (select id from public.sources where title = 'Homebrew Demo' and source_type = 'homebrew' limit 1),
    array['предмет', 'спорядження', 'подорож'],
    'published',
    '2024',
    'homebrew',
    'спорядження',
    'пригодницьке',
    'звичайний',
    '12 зм',
    '8 фунтів',
    false,
    false,
    '{"contains":["мотузка","кресало","сухий пайок"]}'::jsonb,
    null,
    null,
    null,
    null,
    null,
    false,
    '1 набір'
  )
on conflict (slug) do update
set title_ua = excluded.title_ua,
    title_original = excluded.title_original,
    short_description = excluded.short_description,
    full_description_markdown = excluded.full_description_markdown,
    source_id = excluded.source_id,
    tags = excluded.tags,
    publication_status = excluded.publication_status,
    rules_version = excluded.rules_version,
    content_type = excluded.content_type,
    item_type = excluded.item_type,
    category = excluded.category,
    rarity = excluded.rarity,
    price = excluded.price,
    weight = excluded.weight,
    requires_attunement = excluded.requires_attunement,
    is_magical = excluded.is_magical,
    properties = excluded.properties,
    damage = excluded.damage,
    damage_type = excluded.damage_type,
    range = excluded.range,
    armor_class = excluded.armor_class,
    required_strength = excluded.required_strength,
    stealth_disadvantage = excluded.stealth_disadvantage,
    quantity = excluded.quantity,
    updated_at = now();
